# Use an official image
FROM ubuntu:latest

# Set the working directory to /app
WORKDIR /workspace

# Copy the current directory contents into the container at /app
#ADD . /app

# Install any needed packages specified in requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV CONSOLENAME Ubuntu

# Run application when the container launches
#CMD ["python", "app.py"]
